apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api 
  labels:
    app: backend-api
spec:
  selector:
    matchLabels:
        app: backend-api
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: 720766170633.dkr.ecr.us-east-2.amazonaws.com/backend-api:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
